name: Build
on:
    workflow_run: 
        workflows: [Other Branch Build]
        types:
            - completed
jobs:
    build:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - run: echo 'Workflow was triggered by workflow that ran in another branch'
