name: Build
on:
    workflow_run: 
        workflows: [Other Branch Build]
        types:
            - completed
jobs:
    buld:
        runs-on: ubuntu-latest
        steps:
            - run: echo 'Workflow was triggered by workflow that ran in another branch'
